# Generated by Django 2.2.4 on 2019-12-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cube',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('x', models.IntegerField(verbose_name='id')),
                ('y', models.IntegerField(verbose_name='id')),
                ('z', models.IntegerField(verbose_name='id')),
            ],
            options={
                'db_table': 'cube',
            },
        ),
    ]
